FROM instrumentisto/flutter

WORKDIR /app

COPY . /app

WORKDIR /app/brew_it

EXPOSE 8080

#CMD ["flutter", "upgrade"]
#CMD ["flutter", "pub", "get"]
#CMD ["flutter", "run", "-d", "edge", "--web-browser-flag", "--disable-web-security"]
