# Generated by Django 5.0 on 2024-12-29 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('PROD', 'Production Brewery'), ('CONTR', 'Contract Brewery'), ('ADMIN', 'Administrator')], default='ADMIN', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brewery',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='breweries', to=settings.AUTH_USER_MODEL),
        ),
    ]
