# Generated by Django 5.0 on 2024-12-31 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0002_delete_role_account_role_alter_brewery_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='selector',
            field=models.CharField(choices=[('PROD', 'Production Brewery'), ('CONTR', 'Contract Brewery')], max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment', to='brewit_api.brewery'),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='brewit_api.equipment'),
        ),
    ]
