# Generated by Django 5.0 on 2024-12-31 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0003_alter_brewery_selector_alter_equipment_brewery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentreservation',
            name='reservation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='brewit_api.reservation'),
        ),
    ]
