# Generated by Django 5.0 on 2025-01-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0004_alter_equipmentreservation_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatpackaging',
            name='packaging_type',
            field=models.CharField(choices=[('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('KEG', 'Keg')], max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='selector',
            field=models.CharField(choices=[('VAT', 'Vat'), ('BREWSET', 'Brewing Set')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vatpackaging',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vat_packaging', to='brewit_api.equipment'),
        ),
        migrations.DeleteModel(
            name='Packagingtype',
        ),
    ]
