# Generated by Django 5.0 on 2025-01-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0005_alter_vatpackaging_packaging_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='brewery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sectors', to='brewit_api.brewery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='selector',
            field=models.CharField(choices=[('CLEAN', 'Cleaning'), ('BREW', 'Brewing')], max_length=10),
        ),
    ]
