# Generated by Django 5.0 on 2025-01-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0006_sector_brewery_alter_equipmentreservation_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allows_sector_share',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('brew_size', models.IntegerField()),
                ('authorised_workers', models.CharField(blank=True, max_length=512, null=True)),
                ('allows_sector_share', models.BooleanField()),
                ('uses_bacteria', models.BooleanField()),
                ('contract_brewery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_requests_contract', to='brewit_api.brewery')),
                ('production_brewery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brewit_api.brewery')),
            ],
        ),
        migrations.CreateModel(
            name='EqipmentReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations_requests', to='brewit_api.equipment')),
                ('reservation_requestt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brewit_api.reservationrequest')),
            ],
        ),
    ]
