# Generated by Django 5.0 on 2025-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0007_reservation_allows_sector_share_reservationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='allows_sector_share',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
