# Generated by Django 5.0 on 2025-01-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0008_alter_reservation_allows_sector_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationrequest',
            name='uses_bacteria',
        ),
    ]
