# Generated by Django 5.0 on 2025-01-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0009_remove_reservationrequest_uses_bacteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eqipmentreservationrequest',
            name='reservation_requestt',
        ),
        migrations.AddField(
            model_name='eqipmentreservationrequest',
            name='reservation_request',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_reservation_requests', to='brewit_api.reservationrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eqipmentreservationrequest',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_reservation_requests', to='brewit_api.equipment'),
        ),
    ]
