# Generated by Django 5.0 on 2025-01-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0010_remove_eqipmentreservationrequest_reservation_requestt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqipmentreservationrequest',
            name='reservation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservation_requests', to='brewit_api.reservationrequest'),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='reservation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipment_reservations', to='brewit_api.reservation'),
        ),
    ]
