# Generated by Django 5.0 on 2025-01-07 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0011_alter_eqipmentreservationrequest_reservation_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='beer_type_beer',
            new_name='beer_type',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='contract_brewery_brewery',
            new_name='contract_brewery',
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='reservation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='brewit_api.reservation'),
        ),
    ]
