# Generated by Django 5.0 on 2025-01-12 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0012_rename_beer_type_beer_recipe_beer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='execution_logs', to='brewit_api.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contract_brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_contract_brewery', to='brewit_api.brewery'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='production_brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_production_brewery', to='brewit_api.brewery'),
        ),
    ]
