# Generated by Django 5.0 on 2025-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0015_registrationrequest_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
