# Generated by Django 5.0 on 2025-01-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0016_alter_registrationrequest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionlog',
            name='log',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_body',
        ),
        migrations.AddField(
            model_name='executionlog',
            name='boiling_log',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='fermentation_log',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='lagerring_log',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='lautering_log',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='mashing_log',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='boiling_body',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fermentation_body',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lagerring_body',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lautering_body',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mashing_body',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='huj', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='brewit_api.reservation'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='contract_brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='brewit_api.brewery'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='authorised_workers',
        ),
        migrations.RemoveField(
            model_name='reservationrequest',
            name='authorised_workers',
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('identificator', models.CharField(max_length=16)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='brewit_api.brewery')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='authorised_workers',
            field=models.ManyToManyField(related_name='reservations', to='brewit_api.worker'),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='authorised_workers',
            field=models.ManyToManyField(related_name='reservation_requests', to='brewit_api.worker'),
        ),
    ]
