# Generated by Django 5.0 on 2025-01-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0017_remove_executionlog_log_remove_recipe_recipe_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqipmentreservationrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eqipmentreservationrequest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='start_date',
            field=models.DateField(),
        ),
    ]
