# Generated by Django 5.0 on 2025-01-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewit_api', '0018_alter_eqipmentreservationrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='identificator',
            field=models.CharField(max_length=32),
        ),
    ]
